[tools]
go = "latest"
node = "22"
deno = "latest"
uv = "latest"
bat = "latest"
curlie = "latest"
delta = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
gping = "latest"
hyperfine = "latest"
jq = "latest"
lazygit = "latest"
neovim = "latest"
ripgrep = "latest"
shellcheck = "latest"
tree-sitter = "latest"
yq = "latest"
actionlint = "latest"
awscli = "latest"
gh = "latest"
pkl = "latest"
qsv = "latest"
tfsec = "latest"
act = "latest"
gradle = "latest"
starship = "latest"
task = "latest"
"aqua:hashicorp/terraform" = "latest"
"aqua:terraform-linters/tflint" = "latest"
"aqua:mike-engel/jwt-cli" = "latest"
"aqua:tweag/nickel" = "latest"
"aqua:herdrdev/herdr" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
