[tools]
go = "latest"
node = "22"
python = "3.13"
rust = "stable"
deno = "latest"
uv = "latest"
"aqua:k1LoW/runn" = "latest"
"aqua:hashicorp/terraform" = "latest"
"aqua:terraform-linters/tflint" = "latest"
"go:go.uber.org/mock/mockgen" = "latest"
