unbind C-b
set -g prefix C-t
bind C-t send-prefix

set -g default-terminal "tmux-256color"
set -sg escape-time 10
set -g history-limit 50000
set -g base-index 1
set -g mouse on
setw -g mode-keys vi
set -g focus-events on

set -ga terminal-overrides ",xterm-256color:Tc"
set -g pane-base-index 1
set -g renumber-windows on
bind r source-file ~/.config/tmux/tmux.conf

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_show_sync_mode 'on'
set -g @plugin 'arcticicestudio/nord-tmux'

run '~/.config/tmux/plugins/tpm/tpm'
