#!/bin/zsh

alias ..='cd ..'
alias '../..'='cd ../..'
alias '../../..'='cd ../../..'
alias '../../../..'='cd ../../../..'
alias '../../../../..'='cd ../../../../..'
alias l='eza -lbghHimSuU --time-style long-iso --git -s Name'
alias ls='eza -lbghHimSuU --time-style long-iso --git -s Name'
alias ll='eza -lbghHimSuU --time-style long-iso --git -s Name'
alias la='eza -labghHimSuU --time-style long-iso --git -s Name'
alias top='glances'
alias du='dust -r -d 1'
alias df='duf'
alias ping='gping'
alias curl='curlie'
alias g='git'
alias d='docker'
alias dc='docker compose'
alias k='kubectl'
alias c='cargo'
alias vim='nvim'
